$primary_paletteKeyColor = 3a7f9e
$secondary_paletteKeyColor = 667a86
$tertiary_paletteKeyColor = 787397
$neutral_paletteKeyColor = 73787b
$neutral_variant_paletteKeyColor = 71787d
$background = 0f1417
$onBackground = dfe3e7
$surface = 0f1417
$surfaceDim = 0f1417
$surfaceBright = 353a3d
$surfaceContainerLowest = 0a0f12
$surfaceContainerLow = 171c1f
$surfaceContainer = 1b2023
$surfaceContainerHigh = 262b2e
$surfaceContainerHighest = 313539
$onSurface = dfe3e7
$surfaceVariant = 40484c
$onSurfaceVariant = c0c7cd
$inverseSurface = dfe3e7
$inverseOnSurface = 2c3134
$outline = 8a9297
$outlineVariant = 40484c
$shadow = 000000
$scrim = 000000
$surfaceTint = 8dcff2
$primary = 8dcff2
$onPrimary = 003548
$primaryContainer = 004d67
$onPrimaryContainer = c1e8ff
$inversePrimary = 186584
$secondary = b5cad7
$onSecondary = 1f333d
$secondaryContainer = 384c57
$onSecondaryContainer = d1e6f3
$tertiary = c8c2ea
$onTertiary = 302c4c
$tertiaryContainer = 928cb2
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = c1e8ff
$primaryFixedDim = 8dcff2
$onPrimaryFixed = 001e2b
$onPrimaryFixedVariant = 004d67
$secondaryFixed = d1e6f3
$secondaryFixedDim = b5cad7
$onSecondaryFixed = 091e27
$onSecondaryFixedVariant = 364954
$tertiaryFixed = e5deff
$tertiaryFixedDim = c8c2ea
$onTertiaryFixed = 1b1736
$onTertiaryFixedVariant = 474364
$term0 = 343434
$term1 = 8383ff
$term2 = 41dff0
$term3 = 75fcdd
$term4 = 7cb2c8
$term5 = 7dadea
$term6 = 84d5e8
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 70efff
$term11 = c9fff3
$term12 = a6c6d1
$term13 = a2c0f7
$term14 = 8ae9fd
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c7dfff
$mauve = 85c6ff
$red = 8ab5ff
$maroon = abbef0
$peach = e0c2f9
$yellow = d0f9f4
$green = 9cecff
$teal = ace9ff
$sky = a7e4ff
$sapphire = 81d1f8
$blue = 72c6f8
$lavender = 99d3fe
$klink = 2290bf
$klinkSelection = 2190bf
$kvisited = 0086d3
$kvisitedSelection = 0086d3
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b9d7
$kpositiveSelection = 00b9d7
$text = dfe3e7
$subtext1 = c0c7cd
$subtext0 = 8a9297
$overlay2 = 787f84
$overlay1 = 656c70
$overlay0 = 545a5f
$surface2 = 43494d
$surface1 = 32383c
$surface0 = 212629
$base = 0f1417
$mantle = 0f1417
$crust = 0e1316
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
